#!/usr/bin/env bash

set -e

wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | tail -n +2 | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")

connected=$(nmcli -fields WIFI g)
if [[ "$connected" =~ "enabled" ]]; then
    toggle="󰖪  Disable Wi-Fi"
elif [[ "$connected" =~ "disabled" ]]; then
    toggle="󰖩  Enable Wi-Fi"
fi

chosen_network=$(echo -e "$toggle\n$wifi_list" | uniq -u | rofi -dmenu -i -selected-row 1 -p "Wi-Fi SSID: ")

if [[ -z "$chosen_network" ]]; then
    exit
fi

chosen_id="${chosen_network:3}"

if [[ "$chosen_network" == "󰖩  Enable Wi-Fi" ]]; then
    nmcli radio wifi on
elif [[ "$chosen_network" == "󰖪  Disable Wi-Fi" ]]; then
    nmcli radio wifi off
else
    success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."

    saved_connections=$(nmcli -g NAME connection)
    if echo "$saved_connections" | rg -q "^$chosen_id$"; then
        nmcli connection up id "$chosen_id" | grep -q "successfully" && "$success_message"
    else
        if [[ "$chosen_network" =~ "" ]]; then
            wifi_password=$(rofi -dmenu -p "Password: ")
        fi
        nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep -q "successfully" && "$success_message"
    fi
fi
