general.import = ["~/.config/alacritty/themes/themes/hyper.toml"]

[window]
opacity = 0.98
padding = { x = 1, y = 0 }
dynamic_padding = true

[terminal.shell]
program = "/run/current-system/sw/bin/zsh"

[font]
size = 14
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "italic" }
bold_italic = { family = "JetbrainsMono Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
]

[debug]
log_level = "Warn"
